Output commit.gif

Set Shell "bash"
Set FontSize 32
Set Width 1200
Set Height 600

Type "./commit.sh" Sleep 500ms  Enter

Sleep 1s
Down@250ms 2
Sleep 500ms
Enter

Sleep 500ms

Type "gum"

Sleep 500ms
Enter

Sleep 1s

Type "Gum is sooo tasty"
Sleep 500ms

Enter

Sleep 1s

Type@65ms "I love bubble gum."
Sleep 500ms
Alt+Enter
Sleep 500ms
Alt+Enter
Sleep 500ms
Type "This commit shows how much I love chewing bubble gum!!!"
Sleep 500ms
Enter

Sleep 1s

Left@400ms 3

Sleep 1s
