Output ./demo.gif

Set Shell bash

Set FontSize 22
Set Width 800
Set Height 450

Type "./demo.sh"
Enter
Sleep 1s
Type "Walter"
Sleep 500ms
Enter

Sleep 2s

Type "Nope, sorry!"
Sleep 500ms
Alt+Enter
Sleep 200ms
Alt+Enter
Sleep 500ms
Type "I don't trust you."
Sleep 1s
Enter

Sleep 2s

Type "x" Sleep 250ms Type "j" Sleep 250ms
Type "x" Sleep 250ms Type "j" Sleep 250ms
Type "x" Sleep 1s

Enter

Sleep 6s

Type "li"
Sleep 1s
Enter

Sleep 3s
Down@500ms 2
Up@500ms 2
Sleep 1s
Enter


Sleep 6s
